name: Docs to PDF
on:
  workflow_dispatch:
    branches: 
      - master
    paths:
      - './README.md'
    
jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v2
        with:
          input_dir: .
          output_dir: .
          build_html: false
      - uses: actions/upload-artifact@v2
        with:
          name: .
          path: .
